name: Test action

on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

env:
  CHECK_SHELL: |
    while read branch; do
      git checkout -B $branch heads/$branch
      # Get the current branch name
      currentBranch=$(git branch --show-current)
      correspondingTag=${currentBranch#checkout-tags/}
      # Check if there are corresponding branches in tags
      if [[ $tags != *$correspondingTag* ]]; then
        echo "Branch '$currentBranch' is checked out, but it is not in the tags list."
        exit 1
      fi
    done <<< $branches

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Checking out specified tags
        id: checkout-tags
        uses: ./
        with:
          base: 'vuejs/vue' # fake upstream so that we can test the action behaviors
          filter: 'v[2-9]\.[7-9]\.[2-6].*'

      - name: Check if all tags are checked out
        run: |
          tags="${{ steps.checkout-tags.outputs.tags }}"
          branches="${{ steps.checkout-tags.outputs.branches }}"
          ${{ env.CHECK_SHELL }}

  test-staged: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Stage 1
        id: checkout-tags-stage1
        uses: ./
        with:
          base: 'vuejs/vue' # fake upstream so that we can test the action behaviors
          filter: 'v[2-9]\.[7-9]\.[2-6].*'
          stage: 1

      - name: Stage 2
        if: ${{ steps.checkout-tags-stage1.outputs.up-to-date == 'false' }}
        id: checkout-tags-stage2
        uses: ./
        with:
          base: 'vuejs/vue' # fake upstream so that we can test the action behaviors
          stage: 2
          stage2-tags: ${{ steps.checkout-tags-stage1.outputs.tags }}

      - name: Check if all tags are checked out
        run: |
          tags="${{ steps.checkout-tags-stage1.outputs.tags }}"
          branches="${{ steps.checkout-tags-stage2.outputs.branches }}"
          ${{ env.CHECK_SHELL }}
