name: Update Action major tag

on:
  release:
    types: [published, edited]
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Repoint the major tag
        run: |
          LATEST_TAG=$(git tag -l | sort -V | tail -n 1)
          MAJOR=${LATEST_TAG%%.*}
          git config user.name 'Github Actions'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git tag --force -a "${MAJOR}" -m "release: ${MAJOR}"
          git push --force origin "${MAJOR}"
          
          echo "MAJOR=${MAJOR}" >> $GITHUB_ENV

      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.MAJOR }}
